<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Accounts\Pages\" />
    <Folder Include="Components\Shared\" />
    <Folder Include="Data\Model\" />
    <Folder Include="Migration\" />
    <Folder Include="Helpers\" />
    <Folder Include="Repository\IRepository\" />
    <Folder Include="Repository\Repository\" />
    <Folder Include="Service\Extesntion\" />
    <Folder Include="ViewModel\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.8.0" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.8.0" />
  </ItemGroup>

</Project>
